### ISSUE TITLE
Additional features 

### ISSUE THREAD

**Issue by NatPombubpa** [greenelab/lab-website-template#1]
Hi Vince,

Thank you for creating this template. There are several things that might be great to add to this template.

1. Blog/News page: do you think we can add tweets from lab account to this page. I think it would be awesome to have both blog posts and news/tweets from lab account twitter.

2. For each Blog post (or any page): can we add option for discussion/comments (something like Disqus)? 

3. Can we add the instruction on how to add/delete a page? For examples, if a lab wants to add a page for "Tutorials", what do they need to do in order to make sure that everything will work in this new page (edit nav.html, edit _config.yml etc.). 

4. Can we also add the the instruction for adding website logo and necessary favicons for different browsers/platforms?

5. I think this template will be popular. It might be great to have another version for multi-language setup.

Cheers 👍 
Nat

**Comment by vincerubinetti** [comment]
Good suggestions! All but 5) I'm already working on or planning on doing soon.

How do you envision 5) working?

**Comment by cgreene** [comment]
I've used internationalization approaches for django before. It looks like the most widely used approach in jekyll is https://github.com/kurtsson/jekyll-multiple-languages-plugin . It builds multiple versions of a site and stores them at paths associated with the language.

It does look like we'll have to use a github action to deploy to pages after running jekyll build ourselves, since github's jekyll doesn't support plugins: https://github.com/marketplace/actions/deploy-to-github-pages

**Comment by vincerubinetti** [comment]
@NatPombubpa I believe with the latest commit I address all of these but 5). If you're satisfied with how I've included/explained the other features you requested, we can close this issue, and I'll open a new issue to track 5) specifically.

I think 5) will have to wait until a bit later, which I think is okay given the availability of Google Translate built-in to browsers.

**Comment by cgreene** [comment]
Can we create a new issue for internationalization?

**Comment by vincerubinetti** [comment]
https://github.com/greenelab/lab-website-template/issues/5
