### ISSUE TITLE
testing - css issues

### ISSUE THREAD

**Issue by aschuerch** [greenelab/lab-website-template#104]
Awesome template, happy to test it! 

After forking, renaming the repo and publishing as indicated in 'Get Started', the css is missing on my published site. Attempting to build the page on Netlify gives me this error:

```
Your SCSS file `css/all.scss` has an error on line 1: File to import not found or unreadable: palettes. Load path: /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-slate-0.2.0/_sass. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.
```
I've tried changing the permission of the files in the css directory, but to no avail.

**Comment by aschuerch** [comment]
Found it! I needed to adjust `baseurl` in _config.yaml. Maybe good to add this in the 'Get Started' section.

**Comment by vincerubinetti** [comment]
Thanks for testing @aschuerch .

Improper `baseurl` can cause a few issues, but I don't see how it could cause that issue. Could you give more information on what you were doing? Where is your website repo, what is the link to the Netlify preview build, what did you change `baseurl` to, etc. It might help other people debugging in the future.

Also, the issues that `baseurl` does cause aren't exactly obvious or intuitive. The docs have "configuring `baseurl`" pretty front and center, but they don't give a warning that failing to do so can cause unexpected errors. So I will add a generic message like that.

**Comment by aschuerch** [comment]
Thank you @vincerubinetti - the fork is at https://github.com/MMB-UMCU/mmb-bioit/. You'll find the link to the Netlify preview build in the pull requests. We attempted yesterday to further fill in the details for the site - overall a smooth process, for starters and github pro's alike. Once we're a bit further with the site I'll add it to your gallery.
The error that I made with setting the baseurl was that I didn't set it, and I think it is a good idea to add a generic message about unexpected errors.

**Comment by vincerubinetti** [comment]
I rewrote/reworked the getting started page to hopefully be a little clearer, and emphasize the importance of setting `baseurl`.

As for what caused it, I have only a vague idea. It might be related to how Jekyll/Sass looks for imports. Currently I do imports at the top of each SASS file like `@import "theme";`, and maybe Jekyll incorporates `baseurl` when looking for that import (idk why it would since this is happening at build-time, not at run-time). Maybe doing relative imports like `@import "./theme";` would fix it... I'll look into it at some point.
