### ISSUE TITLE
github-pages 226 | Error:  No such file or directory @ dir_chdir - /github/workspace/docs

### ISSUE THREAD

**Issue by xihajun** [greenelab/lab-website-template#114]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/25631641/168920259-25e0aa81-87b2-4391-9899-56de100fc33f.png">
Do you have any idea how to fix that?

**Comment by vincerubinetti** [comment]
I don't understand what that error means, but it's likely due to [GitHub Actions](https://www.githubstatus.com/) being down at the moment:

![image](https://user-images.githubusercontent.com/8326331/168920988-24fcac9e-d1f6-4c3d-aae5-901dcbddba65.png)

Also for things like this, it's helpful if you link to the repository where you're actually experiencing the problem, so we can take a look at the GitHub Actions logs fully and look at your source code.

**Comment by xihajun** [comment]
Thanks for your help! sorry silly me. I should have set the `/root` as the page folder under the github page setting! Also, good point for the github action! 

Many thanks,
Jun

**Comment by vincerubinetti** [comment]
Ah if that's the case, then maybe it wasn't due to Actions being down.

For anyone else stumbling on this issue, setting your GitHub Pages to `main` and `/root` is required per the [Getting Started](https://github.com/greenelab/lab-website-template/wiki/Get-Started#set-up-your-site) section.

I didn't realize that if you kept it as `/docs` it would actually go ahead and try to build it, generating a log with errors. Would've thought it would just tell you right under the dropdown box that there's no `/docs` folder and no site to build.
