### ISSUE TITLE
Layout issue - missing CSS and images

### ISSUE THREAD

**Issue by xihajun** [greenelab/lab-website-template#115]
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/25631641/168922802-d8c6940d-4c35-4e9b-bc41-65c5aa9aa7b7.png">
Hi, sorry for open another issue, but may I kindly ask do you have any ideas what may cause the layout issue?

**Comment by vincerubinetti** [comment]
Did you set your `baseurl` properly in `config.yaml`, per [this section of the docs](https://github.com/greenelab/lab-website-template/wiki/Get-Started#set-up-your-url)? The screenshot above is what it looks like when you don't set `baseurl`, because basically the browser cannot find the CSS (styles) or asset (images) files.

**Comment by xihajun** [comment]
Thanks @vincerubinetti  it works now! Silly me :P
