### ISSUE TITLE
Failing to add manual references to citation

### ISSUE THREAD

**Issue by batmen-lab** [greenelab/lab-website-template#116]
I tried to add manual references as citation to sources.yml and failed. Here is the error message:

Generating csl_item for 'raw:files/refs/dance.json' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'raw:files/refs/dance.json'
Couldn't parse Manubot response
Error: Process completed with exit code 1.

Here is what I did: I add a new record with "id: raw:files/refs/dance.json" where the CSL-JSON is manually written and put under the local files/refs/ folder, as suggested by https://github.com/manubot/manubot#manual-references-1. Is there any suggestions or examples how to do that correctly? Thanks!

I also noticed that "users can manually provide the correct metadata using common reference formats." according to https://greenelab.github.io/meta-review/#citation-by-identifier. Is there any examples how to do that? 

An alternative question is how to add conference proceeding papers (e.g. ICML) without any DOI information? Thanks! 

Yang Lu

**Comment by vincerubinetti** [comment]
This is more of a Manubot question but I will try to help.

The first thing to note is that Manubot is not just a single thing, it's a suite/ecosystem. It has several tools, and different workflows under which you'd use them. In this template, we're only using the `manubot cite` functionality. The ["manual references"](https://github.com/manubot/manubot#manual-references-1) readme section you linked is under the "Pandoc filter" functionality. 

`manubot cite` does have a `--bibliography` flag where you can provide a file for manual citation data. But the template [doesn't use](https://github.com/greenelab/lab-website-template/blob/main/auto-cite/util.py#L141-L149) this flag, because there is already a way to provide manual citation directly with the template. This page of the docs explains how:

https://github.com/greenelab/lab-website-template/wiki/Citations#basic-use

Whatever the content of your `files/refs/dance.json` file is, just move it to `sources.yaml` like this:

```yaml
- id: 1234
  title: Some Paper Title
  author: Yang Lu
  publisher: Cold Spring Harbor
```

(Note that for now, due to [this oversight](https://github.com/greenelab/lab-website-template/issues/117), please make sure you put a unique id field even if you don't have a real id for the paper. Hopefully I will fix this in a few days.)

**Comment by vincerubinetti** [comment]
> An alternative question is how to add conference proceeding papers (e.g. ICML) without any DOI information? 

Regarding this question, again see [this section of the docs](https://github.com/greenelab/lab-website-template/wiki/Citations#sourcesyaml). Manubot supports many ways to cite a paper besides `doi`. If the ICML provides any kind of established reference number for the proceeding papers (maybe `ISSN`?), try using that. Then if that doesn't work, you can also use a `url`. Then as a last resort, you can manually input citation data as described in my comment above.

**Comment by vincerubinetti** [comment]
Hi @batmen-lab , did this answer your question?

**Comment by batmen-lab** [comment]
The question was perfectly answered and problem solved! Thanks!
