### ISSUE TITLE
Make automatic citations work on master/main?

### ISSUE THREAD

**Issue by aditya-sarkar441** [greenelab/lab-website-template#17]
I added the doi numbers along with doi links in the /_data/research-input.yml and then commited those changes. After that I pushed it to main branch. However, The github was facing problem building the website. The error was "Page build failed.". Please take a look at this.

**Comment by cgreene** [comment]
Hi @aditya-sarkar441 - can you put a link to the repo where you're seeing this in the github issue?

**Comment by vincerubinetti** [comment]
GitHub wont automatically build your citations for you unless you are working from a pull request. If you want to work directly on master/main, you'll have to [run the automatic citation script manually](https://github.com/greenelab/lab-website-template#automatic-citations) on your computer.

**Comment by aditya-sarkar441** [comment]
> GitHub wont automatically build your citations for you unless you are working from a pull request. If you want to work directly on master/main, you'll have to [run the automatic citation script manually](https://github.com/greenelab/lab-website-template#automatic-citations) on your computer.

Ohh I tried to build it on the master. I'll have to then run it manually on my computer first. Thanks !!

**Comment by aditya-sarkar441** [comment]
> Hi @aditya-sarkar441 - can you put a link to the repo where you're seeing this in the github issue?

Actually, I have reverted that commit. However, the link to our github repo is https://github.com/Mangul-Lab-USC/Mangul-Lab-USC.github.io.

**Comment by vincerubinetti** [comment]
I might be a bit hazy right now, but now that I think about it, we might be able to make it so that it does work on main/master. I'll have to think about it. Renaming this issue to a feature request.

**Comment by cgreene** [comment]
@aditya-sarkar441 : have you considered doing this via a pull request model? That would give you the opportunity to see the results before pushing to master. We generally avoid pushing to master with something that deploys automatically.

**Comment by aditya-sarkar441** [comment]
@cgreene I didn't know about the pull request model. I'll have to look at it. Thanks !!

**Comment by vincerubinetti** [comment]
Idk how long it's been this way, but the gh-actions workflow does trigger on `push`, which means it should work to push to master/main.

If someone is working from pull requests, the citations will automatically generate. Then when they merge it to main, the citation generation will run again, but the output should be the same, and thus nothing will be committed, and thus there will be no duplicate commit.

I've tested this with pull requests and committing straight to `main` on my own copy of the template, and it seems to work.

Also, i've [updated the gh-actions workflow](https://github.com/greenelab/lab-website-template/blob/main/.github/workflows/update-research.yml) such that there shouldn't be 2 action triggers on pull requests (1 for `pull_request` and 1 for `push`) like it previously did because now `push` only triggers on `main`.
