### ISSUE TITLE
updated template, now get warning when creating PR

### ISSUE THREAD

**Issue by aaronjnewman** [greenelab/lab-website-template#199]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/NeuroCognitiveImagingLab/NCIL-website-23

### Version of Lab Website Template you are using

1.1.5

### Description

I followed [your instructions](https://greene-lab.gitbook.io/lab-website-template-docs/advanced/update-your-template) for updating the template based on the "generated" method. I resolved all the merge conflicts and my website looks fine. 

The issue arose when I tried to make new edits in a new branch and then create a PR. When I do so, I see the text below auto-populated into the comment. 

I obviously don't want to mess with your template... is this a bug (i.e., a false warning) or maybe a consequence of adding the template as a remote? Suggestions how to address it?

thanks

```

STOP!!!

You are about to open this pull request against THE TEMPLATE ITSELF. You probably meant to open it against your own website repo.

---

FOR THE TEMPLATE MAINTAINER(S)

New template version checklist:

- [ ] I have updated CITATION and CHANGELOG as appropriate.
- [ ] I have updated lab-website-template-docs as appropriate.
- [ ] I have checked the testbed as appropriate.
```

**Comment by vincerubinetti** [comment]
[Your repo still has `pull_request_template.md` and `user_pull_request_template.md`.](https://github.com/NeuroCognitiveImagingLab/NCIL-website-23/tree/main/.github)

GitHub reads `.github/pull_request_template.md` (from whatever repo you are trying to merge _into_) to show that default comment when opening a PR.

The template itself needs to have one of these to warn people not to open PRs against it, because the [GitHub UI misleads people into doing so accidentally](https://github.com/orgs/community/discussions/11729#discussioncomment-5072461). But when users are merging a PR into their own copy of the template, that warning is not applicable and confusing.

From the [instructions page you linked](https://greene-lab.gitbook.io/lab-website-template-docs/advanced/update-your-template#from-pre-release): 

> go through the merge instructions below, then go **run the setup instructions** and custom domain instructions if applicable.

The setup instructions, among other things, automatically replaces `pull_request_template.md` (for the template itself) with the `user_pull_request_template.md`. If you go through the setup, and also make sure you're merging PRs into your own `main` branch and not the template itself, that warning should go away.

**Comment by aaronjnewman** [comment]
OK, I understand. However, I think what's confusing is that the "run setup instructions" bit in the documentation is under the heading, "[Update your template] From pre-release" - but I was not updating from pre-release, I was updating from v 1.1.0... so I didn't think those instructions applied. And I didn't have this problem until I updated to 1.5.0. So I think maybe merging in the updates may have brought back the template's `pull_request_template.md` file over as well? Or should the `first-time-setup` action be run every time you update?
Thanks again!

**Comment by vincerubinetti** [comment]
That's a fair point. If you're updating from any version to another, you might pull back in those pr template files, as well as other [unneeded files](https://github.com/greenelab/lab-website-template/blob/main/.github/workflows/first-time-setup.yaml#LL53C1-L59C47) like testbed.md and changelog, erroneously.

I'll try to make this clearer in the "Update your template" and "Repo structure" pages.

**Comment by aaronjnewman** [comment]
Thanks - I agree that at least a little update to the docs would help. What about creating a variant of the first-time-setup action specific for template updates? I wouldn't want my README replaced every time I update...
thanks again

**Comment by vincerubinetti** [comment]
I've made updates to the documentation to address this here:
https://github.com/greenelab/lab-website-template-docs/commit/29a20263df36a390976fd03677a6e5b89ccf3e31

One of my goals with this template is to keep the number of files at an absolute minimum. As such, I don't want to add a whole new template-update workflow essentially just to do the remove and rename steps (and duplicate them) from the first-time-setup workflow. The user would also have to remember to run the workflow after every update once they've pushed it to GitHub, and the files would be there in a commit. Instead, I think it's more appropriate to add notes about these files to the merge instructions that the user already has to do anyway.

I've also kept the "re-run the first-time-setup" to just the "coming from pre-release section", as it does do a lot of resetting of the readme, config, and homepage that updating users wouldn't want, as you said. Pre-release convert users still need to run it because it does a bunch of other necessary things like create a gh-pages branch.
