### ISSUE TITLE
Integrate with Lightbox for photo galleries

### ISSUE THREAD

**Issue by shainova** [greenelab/lab-website-template#228]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://github.com/Ecological-Complexity-Lab/lab_website

### Version of Lab Website Template you are using

1.1.6

### Description

Thanks for this amazing template!! I would like to integrate a photo gallery. https://lokeshdhakar.com/projects/lightbox2/ looks promising. However, every time I edit a md it removes all the html. I can directly edit the gh-pages branch but this gets over written and does not seem right to do. Is there a way to integrate lighbox?

**Comment by vincerubinetti** [comment]
> However, every time I edit a md it removes all the html. 

I don't know what you mean by this. Any HTML you include in a markdown file will stay there. All markdown parsers (as far as I'm aware) convert any plain markdown content to HTML, and leave any blocks that are already HTML as HTML.

I see on your site, the HTML you've put on the gallery page is indeed there:

https://ecomplab.com/gallery/

<img width="1066" alt="Screenshot 2023-12-18 at 2 24 29 PM" src="https://github.com/greenelab/lab-website-template/assets/8326331/00cbe23b-8dfc-420f-8eef-9254510cd858">

If you're talking about why your images are not appearing, that's because the way you've written the link to an image makes the browser look for the image relative to the current path, at `https://ecomplab.com/gallery/images/image2.jpg`. What you wanted is `https://ecomplab.com/images/image2.jpg`.

See [this section of the docs](https://greene-lab.gitbook.io/lab-website-template-docs/basics/write-basic-content#advanced).

**Comment by vincerubinetti** [comment]
Closing this as looking at your gallery page at the moment it seems that you've fixed this.

**Comment by shainova** [comment]
Yes, just did this yesterday. Thank you!
