### ISSUE TITLE
first-time-setup node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by jonbakerlab** [greenelab/lab-website-template#238]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Version of Lab Website Template you are using

1.2.0

### Description

Following the instructions in your docs to setup a lab website using your template, and I'm getting the following error when running the first-time-setup action:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: peterjgrainger/action-create-branch@v2.4.0, actions/checkout@v3, stefanzweifel/git-auto-commit-action@v4, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

Browser is Safari 17.1

**Comment by vincerubinetti** [comment]
Is this error preventing folks from building/updating their sites? I'm hoping this is just a warning. 

The fix for this should hopefully just be to update the versions of all the actions being used in the workflows. Node, and by extension Actions, really seems to deprecate Node versions quickly; tough to stay on top of.

**Comment by ytakemon** [comment]
Hi @vincerubinetti - For me it's just a warning. I am still able to build/update the site.

**Comment by eastonwhite** [comment]
The build actually fails for me when adding new sources to cite. 

Auto Cite
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by vincerubinetti** [comment]
If your build is failing, please link to your repo and ideally the log of the gh action workflow that is failing so I can take a look at it.

**Comment by kdkorthauer** [comment]
My build is failing when I'm trying to update my site, too.

https://github.com/korthauer-lab/korthauer-lab.github.io

https://github.com/korthauer-lab/korthauer-lab.github.io/actions/runs/8024159402

**Comment by vincerubinetti** [comment]
I'm quite certain this particular warning should only ever be a warning, and not the reason someone's build is failing. They haven't fully removed Node 16 support yet, this is an early warning. By spring, though, when they actually remove support, this would cause things with the template to break.

---

@kdkorthauer Your build isn't failing because of the node.js 16 issue:

![image](https://github.com/greenelab/lab-website-template/assets/8326331/238d5e21-3992-4823-adb8-3e93b4a0a635)

In your specific case, you have several critical errors in your logs:

```shell
Processing source 37 of 42, id: wosuid:WOS:000209142900506
## WARNING
Generating csl_item for 'wosuid:WOS:000209142900506' failed due to a NotImplementedError:
Manubot does not know how to generate a csl_item for 'wosuid:WOS:000209142900506'
    Using Manubot to generate citation
            Couldn't parse Manubot response
```

Your orcid produces source identifiers like `wosuid` that Manubot is unable to cite.

See these issues:

https://github.com/greenelab/lab-website-template/issues/186
https://github.com/greenelab/lab-website-template/pull/185

You can uncomment the [`continue` line in `cite.py` here](https://github.com/greenelab/lab-website-template/blob/main/_cite/cite.py#L151) to move that from being an error to just a warning (that you would have to open the github action logs to find). I may make that the default behavior in the upcoming v1.2.0 of the template.

**Comment by kdkorthauer** [comment]
@vincerubinetti Thank you for pointing that out!
