### ISSUE TITLE
Fetching papers from author's ORCID but only on a specific period of time

### ISSUE THREAD

**Issue by hilder-vitor** [greenelab/lab-website-template#271]
### Checks

- [X] I have searched **[the docs](https://greene-lab.gitbook.io/lab-website-template-docs)**, [existing issues](https://github.com/greenelab/lab-website-template/issues), and [existing discussions](https://github.com/greenelab/lab-website-template/discussions) for answers first.

### Link to your website repo

https://hilder-vitor.github.io/hello-world/

### Version of Lab Website Template you are using

1.2.2

### Description

When we put a list of ORCIDs in the file _data/orcid.yaml, the page Research is created with all the papers of each author whose orcid is given. 

However, imagine a professor who stayed in the lab for 4 years, say, from 2018 to 2022, then he moved to another university. In this case, I would like to include his ORCID in the yaml file, so that his papers are fetched automatically, but I do not want to show all the papers, but only the ones from those 4 years (which are the papers he published while still in the lab).

Is there a way of doing that? Maybe instead of just listing his ORCID, I could write somethin like
- orcid: 0100-XXXXXXXX
   - from: 2018-01-01
   - to: 2021-12-31
   
Thank you!

**Comment by hilder-vitor** [comment]
I realized I posted the website link instead of the repository... So the repo is this one: https://github.com/hilder-vitor/hello-world

**Comment by vincerubinetti** [comment]
You can probably accomplish what you want with [list component filters](https://greene-lab.gitbook.io/lab-website-template-docs/basics/components/list#filters), e.g. on your research page in a `{% include list.html %}`, use `filters="date: 2018, date: 2019, date: 2020, date: 2021"`. It's a bit of a pain but it works.

Right now, there isn't a way to filter the citations _on the side of the cite process_ (i.e. the filtered out sources never even get output to `citations.yaml`). But it'd probably be not too hard for you to add this functionality to your template's `_cite/cite.py`:

```python
    # add this (UNTESTED)
    date = get_safe(citation, "date", "")
    _from = get_safe(citation, "from", "")
    to = get_safe(citation, "to", "")
    if date and _from and to and date >= _from and date <= to:
        continue

    # add new citation to list
    citations.append(citation)
```

I probably wouldn't add this `from`/`to` functionality to the template, unless a lot of people request it. You might want a date range, but someone else might want to just exclude a year, and someone else might want to take just the last three years, and eventually we'd end up with a dozen different special fields/options in the cite process. 

If the list component filtering doesn't work well enough for some reason, and people really want to filter out citations before they make it into `citations.yaml`, I'd try to implement filtering in a more flexible and generic way.

**Comment by hilder-vitor** [comment]
Hello! Thanks for the answer! But I don't understand how it would work... 

Using a filter per date on `{% include list.html %}` would filter out all the papers not included in the given year list, right? Not only the papers from the member who left the lab. 

And the second solution, editing the Python script, I don't understand exactly where it takes the `_from` and the `to` variables from, I think it it takes from the paper metadata itself, right?  But anyway, since it has no `if` using the author orcid, I assume it will also ignore all the papers not falling in the given range instead of just ignoring the papers of the member who left the lab...

**Comment by hilder-vitor** [comment]
Maybe in my first comment I have not explained well the problem... The situation I am considering is that of a professor who stayed in the lab for a few years, then left the lab (moved to another university, for example). If I leave this professor's orcid in the orcid.yaml file, then all his papers, including the recent ones, which he published already in another lab, will be displayed in the list of publications of my lab. 

Thus, for this specific professor, I would like to only show the papers corresponding to the period he was in the lab. For all the other professors, I would like to continue showing all the papers, of course.

**Comment by vincerubinetti** [comment]
Okay, I didn't realize you were definitely trying to keep all the ORCID papers in a single list on the research page. A lot of times, since ORCIDs can generate a really long list of papers, people will list their ORCID papers on their bio page and leave the research page for just a hand-curated list of papers.

The [list filter](https://greene-lab.gitbook.io/lab-website-template-docs/basics/components/list#filters) and [orcid citation](https://greene-lab.gitbook.io/lab-website-template-docs/basics/citations#orcid) mechanisms of the template are quite flexible. Note that you can provide multiple filters per list.

However, currently the list filters are all "AND"s, and to achieve what you want in a single `{% include list.html %}`, we'd need more sophisticated filtering. Let's call the professor that left Professor X. You could "tag" their orcid like `- orcid: xxxx-xxxx-xxxx-xxxx\n  professor-x: true` and do a list with `filters="professor-x: true, date: ^(2018|2019|2020|2021)"` (see the docs pages I linked above). But this would show ONLY Professor X and their papers in those years. Normally I would say, do this, then do another list component above it with `filters="professor x: "` to capture the inverse, but you probably don't want to show all that professor's papers at the bottom or top of the research page.

I will try to think how the `filters` system could be extended to do more complex logic... like... `filters="professor-x: OR (professor-x: true AND date: ^(2018|2019|2020|2021))"`. This could become quite complex and error prone. Maybe we could make use of Ruby's `eval` function, so the user could provide any Ruby expression for filtering, like `filter="!item['professor-x'] or /^(2018|2019|2020)/.match?(item['date'])"`. Not sure if this is jumping the shark.

> And the second solution, editing the Python script, I don't understand exactly where it takes the _from and the to variables from, I think it it takes from the paper metadata itself, right? But anyway, since it has no if using the author orcid, I assume it will also ignore all the papers not falling in the given range instead of just ignoring the papers of the member who left the lab...

This is not correct. I wrote those lines of python to match what you were suggesting in your first post. If you put a `from` and `to` field on just one ORCID entry, all of the papers that come out of that will be tagged with the `from` and `to` (again, see the docs pages linked above). The code then checks _if both those fields are present/defined_, and if they are, then check if date is within them, and if it's not, discard the citation (don't append it to the list).

So in your case, for now, I would recommend adding those lines of python to your cite script.

**Comment by vincerubinetti** [comment]
See this feature proposal: https://github.com/greenelab/lab-website-template/issues/272

In your case, on your research page, you would use it like `filters="orcid == 'xxxx-xxxx-xxxx-xxxx' ? date =~ ^(2018|2019|2020|2021) : true"`.
