### ISSUE TITLE
Change list component `filters` to Ruby expression?

### ISSUE THREAD

**Issue by vincerubinetti** [greenelab/lab-website-template#272]
See #271 for motivation behind this. Sometimes we need more complex logic for filtering, and trying to make our own syntax for this will be brittle and an [anti-pattern](https://en.wikipedia.org/wiki/Inner-platform_effect).

I think it might be best to simply have `filter` take any Ruby expression that evaluates to true/false. The, under-the-hood, we can use [eval](https://apidock.com/ruby/Kernel/eval) and define all fields on an item as local variables in the evaluation.

So, the user could provide something like `filter="publisher == 'bioRxiv' and date =~ /^2020/"` (all papers published by bioRxiv in 2020) or `!alumni ? true : date =~ /^2024/` (keep all papers by current lab members, but only show 2024 papers for alumni team members).

This is way more flexible, and perhaps more intuitive and readable. For example, compare `role == 'programmer' and alumni == true` (proposed syntax) to `role: programmer, alumni: true` (current syntax). Ruby syntax in general, imo, is not very intuitive, but for simple things it's fine. A user would probably have to look up that they need `=~` for regex unless they happen to know Ruby. 

Also, I'd want to rename this param `filter` (since it's only one condition and to force users to notice that the behavior has changed if they don't update their syntax after updating their template version) and deprecate `filters` (I don't want to have two params that look almost the same with two very different behaviors).

Users, please indicate whether you would like or dislike this change with a 👍 or 👎 .

**Comment by vincerubinetti** [comment]
<details> <summary>Here is some code I've been experimenting with</summary>

```ruby
filter = "alumni ? true : date =~ /^2024/"

data = [
	{"author" => "Jane Smith", "date" => "2015-01-01"},
	{"author" => "John Smith", "date" => "2019-02-01"},
	{"author" => "Ada Lovelace", "date" => "2020-03-01", "alumni"=> true},
	{"author" => "Alan Turing", "date" => "2021-04-01", "alumni"=> true},
	{"author" => "Marie Curie", "date" => "2024-05-01"},
]

def empty_binding
	binding
end

def data_filter(data, filter)
	if not data.is_a?(Array) or not filter.is_a?(String)
		return data
	end
	data = data.clone.select!{
		|d|
		b = empty_binding
		d.each do |var, val| b.local_variable_set(var, val) end
		keep = true
		while true
			begin
				keep = !!eval(filter, b)
				break
			rescue NameError => e
				b.local_variable_set(e.name, nil)
			end
		end
		keep
	}
	return data
end

print data_filter(data, filter)
```

</details>

**Comment by hilder-vitor** [comment]
This looks very flexible and I think it doesn't complicate things from the user point of view. So, it looks good! 

Would it be possible to use variables to compose the years inside the pattern to be matched? So if we had 

`{"author" => "Ada Lovelace", "date-joined" => "2020-03-01", "date-left" => "2022-10-01", "alumni"=> true}`

we filter as

`filter = "!alumni ? true : (date-joined <= date-publication and date-publication <= date-left)"`

instead of hard writing the date interval? 

I asking this just because if someone tries to scale this solution for two or more members who left the lab, they would need to hard write the years of each of them in the filter pattern and that would get very complicated.

But for sure, for one single member, this solution works fine. And also, it is more general than that, so it can be used to filter things in other scenarios, so I like it anyway. 

By the way, thank you very much the effort!

**Comment by vincerubinetti** [comment]
With this solution, you could use any valid Ruby expression. So you could go as wild as you want.

I'm very inexperienced with Ruby, but I think you could just do this `date.between?("2019", "2023")`, or `date.between?(date_joined, date_left)`.

Note the last few sentences of [this comment above](https://github.com/greenelab/lab-website-template/issues/272#issuecomment-2259548643), though. You won't be able to do `date-joined < date-publication`, because `date-joined` isn't a valid variable name in Ruby (or most languages). So my demo code above converts it to `date_joined` automatically. Or you could use `item["date-joined"]`.

**Comment by hilder-vitor** [comment]
I played a little with the `between?` and it seems to work fine (:
