### ISSUE TITLE
Confusing publication sort order

### ISSUE THREAD

**Issue by cgreene** [greenelab/lab-website-template#8]
I expected publications to be sorted in a date order with the most recent first, but I'm not able to easily see how that sort is happening.

![Screen Shot 2020-11-10 at 11 41 14 AM](https://user-images.githubusercontent.com/542643/98703701-c505ab80-2349-11eb-8c66-877405efbbf0.png)

**Comment by vincerubinetti** [comment]
This is most likely due to the Jekyll/Liquid sorting algorithm sorting the dates as strings rather than numbers. You can see that it shows September (09) first, all the way down to January (01), then December (12) to October (10).

Javascript has the same unfortunate behavior: `['5', '9', '11', '12'].sort()` -> `["11", "12", "5", "9"]`

Should be fixable by padding a `0` at the start for single digits.
