### ISSUE TITLE
is there a way to build the page with the native github.io?

### ISSUE THREAD

**Issue by jxchen01** [greenelab/lab-website-template#80]
like this https://medium.com/@svinkle/publish-and-share-your-own-website-for-free-with-github-2eff049a1cb5

My understanding is that github.io supports jekyll themes. There might be a way to build the webpage using github action and release on lab-name.github.io

**Comment by vincerubinetti** [comment]
Hi @jxchen01 

I can't read the article because it requires a log in, but if I'm understanding your request... that is how the template currently works. It deploys automatically, without any github actions, to `lab-name.github.io/lab-website`. That is the main intended use case. If you're talking about making the website be at `lab-name.github.io` directly, I believe you do it the same way, except you just make sure to name the repo `lab-name.github.io`.

If you are talking about supporting different Jekyll themes in this template, but still keeping the other functionality like auto-citations, that's not something we plan to support.

**Comment by jxchen01** [comment]
@vincerubinetti thanks for your swift reply. I don't mean different Jekyll template, just the current one in the template. 

Currenly, I can see the webpage looking good after running through netlify. See https://mystifying-bell-83a659.netlify.app/

But, if I view the webpage directly (see : https://mmv-lab.github.io/), it looks like the picture below:

![image](https://user-images.githubusercontent.com/7811075/121763538-b8208480-caf1-11eb-855e-4d66c7b73ec5.png)

I was thinking maybe netlify did some building steps, but native github page did not? 

Thanks,
Jianxu

**Comment by jxchen01** [comment]
I think I figure out the issue. 

It looks like the current template does not support making the webpage available at `lab-name.github.io`, and only supports `lab-name.github.io/lab-name`, due to the base url setting.

for example, if name my repo as "my-lab.github.io", what should I put for `baseurl` in `_config.yaml`? I assume the baseurl refers o the repo name, except cannot use the repo the same as `my-lab.github.io`. 

I am not sure if I made this issue clear. In short, some special setting on the `baseurl` may be needed if users want to deploy the page at `my-lab.github.io`

**Comment by vincerubinetti** [comment]
The template does support hosting it there, but the documentation could be updated to include this option. Simply set `baseurl` to `""`. It is essentially the same instructions as [this section of the docs](https://github.com/greenelab/lab-website-template/wiki/Get-Started#hook-up-a-custom-domain).

I will add a new section called something like _Host your site at `your-lab.github.io/`_.

**Comment by vincerubinetti** [comment]
I've added an example of a user site `baseurl` in the docs here:
https://github.com/greenelab/lab-website-template/wiki/Basic-Editing#config-file
