### ISSUE TITLE
no default 'join' folder

### ISSUE THREAD

**Issue by hyphaltip** [greenelab/lab-website-template#98]
The team page links to a /join link but this is not populated in the default template - maybe add one?
[@QuantMarineEcoLab site looks nice!](https://github.com/QuantMarineEcoLab/quantmarineecolab.github.io/blob/main/join/index.md)

**Comment by vincerubinetti** [comment]
I actually want to discourage people to simplify their headers and not split up their sites into too many top-level pages, per #86 . So in an upcoming PR I'm going to instead just put some actual "join" placeholder text rather than a link to a non-existent "join" page. 

[Greene Lab](https://greenelab.com/) does have a dedicated join page, but most of the labs seen so far aren't big enough to need it; it can more appropriately just fit on the team page.

Of course users can easily add it and link to it on their own if they need it.

**Comment by hyphaltip** [comment]
okay - that also makes sense, I just wanted to deal with something that was incomplete when I was starting to customized a local install.
